### ISSUE TITLE
Error while trying to use with rollup

### ISSUE THREAD

**Issue by rjnair-nm** [ilearnio/module-alias#10]
Since, i am doing server side rendering with Rollup, i am using module-alias to create aliases for react with preact-compat. This has been mentioned in one of the threads as well.
https://github.com/developit/preact-compat/issues/299#issuecomment-280499913

I have the below alias in my node server file :-

```
require('module-alias').addAliases({
  'react': 'preact-compat',
  'react-dom': 'preact-compat'
})
```

However i still get the error stating `Error: Cannot find module 'react'`

**Comment by ilearnio** [comment]
Pretty strange, such simple aliases should work fine. I would glad to help you but I have a lot going on, so don't really have time. There's not much of code it the plugin so if could submit a PR that would be super awesome

**Comment by danielgormly** [comment]
@rjnair-nm I have a similar issue with Preact. It's because I'm using an npm module which is still brought in externally from the `node_modules` folder even from the server build, because I'm not using `rollup-plugin-node-resolve` there. So it is still trying to look for React in `node_modules` via the component also in `node_modules`.

On the server without the use of nodeResolve something like this [module-alias](https://www.npmjs.com/package/module-alias) is preferable. Or maybe Rollup's `path` option though I'm not quite sure that it works that way. Working on a solution now.
