### ISSUE TITLE
Is it good to use this package for my project?

### ISSUE THREAD

**Issue by Zt-freak** [ilearnio/module-alias#131]
Hi, I read in the readme that it's not a good idea to use this package if you want to publish an NPM package, but what if your package is going to be installed globally as a CLI, is it ok to use this?

If not, is there another way to get path aliases to work? I keep getting module not found errors when I load up my application.

**Comment by Kehrlann** [comment]
Hi @Zt-freak ,

Cli apps should be fine. The warning, as in  “you _can_ use this but there are limitations” is for code that is _loaded by other code_, because:
- module-alias depends on some well known paths to find the alias (hence the caveat about `register` in the README
- it may conflict with aliases in end-user projects
- If multiple versions of module-alias are in node_modules, this is undefined behavior.


Hope this helps !

**Comment by Zt-freak** [comment]
@Kehrlann thank you for the information.
