### ISSUE TITLE
addPath in '-r script': require.main.paths undefined

### ISSUE THREAD

**Issue by gkraser** [ilearnio/module-alias#40]
Error in `addPath`, if script in `-r` option.

Script (test.js):
```js
require("module-alias").addPath('.')
```
run:
```
node -r ./test.js
```
error: 
```
    addPathHelper(path, require.main.paths)
                                     ^

TypeError: Cannot read property 'paths' of undefined
    at Function.addPath (node_modules\module-alias\index.js:85:38)
```
run as simple script - no error:
```
node ./test.js
```

**Comment by ilearnio** [comment]
You're doing it wrong. You forgot to call the initializing function. This is how it should be

```js
const moduleAlias = require('module-alias')('.') // <-- path to app's root
moduleAlias.addPath('~', __dirname)
```

or use with `/register` which will do the initialization for you, useful in es modules

```
import moduleAlias from 'module-alias/register'
moduleAlias.addPath('~', __dirname)
```

**Comment by shlomiassaf** [comment]
@ilearnio I think your answer might be wrong.

When `addPath()` is called in a preloaded startup module (`-r`, `--require`) it is called **before** the main module has loaded and so `require.main` is not populated yet, which is why the error happen.

It is also misleading because `init()` returns undefined which means that `require('module-alias')('.')` returns `undefined` as well as `import moduleAlias from 'module-alias/register'`

**Comment by ivancuric** [comment]
Same issue here. I'm using the following file to use babel-typescript:
```
// babel-register.js
require('@babel/register')({ extensions: ['.js', '.jsx', '.ts', '.tsx'] });
```
Which is then used like this in package.json:
```
"build-diagnostic-tools": "node -r ./babel-register.js ./_scripts/build-diagnostic-tools.ts",
```

This is the go-to usage when you want to use typescript with babel.
Would be great if I could just put this in the `babel-register.js` instead of in every file that it's being used in.
